services:
  legal-api:
    build: .
    entrypoint: "nodemon --watch \"src/**\" --ext \"ts,json\" --exec \"ts-node src/index.ts\""
    container_name: legal-api
    volumes:
      - ./:/app
      - ./.vol/tmp:/tmp
    links:
      - legal-api-db
      - legal-api-db-test
    ports:
      - "8888:80"
    environment:
      PORT: 80

  legal-api-db:
    image: mysql:oracle
    container_name: legal-api-db
    ports:
      - "3306:3306"
    volumes:
      - ./.vol/legal-api:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

  legal-api-db-test:
    image: mysql:oracle
    container_name: legal-api-db-test
    ports:
      - "3307:3306"
    volumes:
      - ./.vol/legal-api-test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
